name=microStore
version=0.1.7
author=Chad Attermann <attermann@gmail.com>
maintainer=Chad Attermann <attermann@gmail.com>
sentence=A high performance single-header embeddable persistent key-value store for constrained devices with indexing capabilities and time-based pruning.
paragraph=
category=Database
url=https://github.com/attermann/microStore.git
architectures=*
depends=
