; PlatformIO Project Configuration File
; https://docs.platformio.org/page/projectconf.html

[env]
monitor_speed = 115200

[common]
build_unflags =
	-std=gnu++11
build_flags =
	-std=gnu++14
lib_deps =
extra_scripts =

[env:native]
platform = native
build_unflags =
    ${common.build_unflags}
build_flags =
    ${common.build_flags}
    -DPLATFORM_NATIVE
    -DUSTORE_USE_POSIXFS
    -DUSTORE_USE_STDIOFS
    -DUSTORE_USE_UNIVERSALFS
    -DUSTORE_USE_NOOPFS
lib_deps =
	${common.lib_deps}
lib_compat_mode = off

[env:native_debug]
platform = native
build_unflags =
	${common.build_unflags}
build_flags =
	${common.build_flags}
	; CBA TEST
	;-fsanitize=address
	-fno-omit-frame-pointer
	-g
	;-O1
	-O0
    -DPLATFORM_NATIVE
    -DUSTORE_USE_POSIXFS
    ;-DUSTORE_USE_STDIOFS
lib_deps =
	${common.lib_deps}
lib_compat_mode = off

[env:ttgo-lora32-v21]
framework = arduino
platform = espressif32
board = ttgo-lora32-v21
upload_speed = 460800
board_build.partitions = no_ota.csv
board_build.filesystem = littlefs
build_unflags =
    ${common.build_unflags}
build_flags =
    ${common.build_flags}
    -DPLATFORM_ESP32
    -DUSTORE_USE_LITTLEFS
    -DUSTORE_USE_SPIFFS
    -DUSTORE_USE_SD
    -DUSTORE_USE_UNIVERSALFS
	-DSDCARD_SCLK=14
	-DSDCARD_MISO=2
	-DSDCARD_MOSI=15
	-DSDCARD_CS=13
lib_deps =
    ${common.lib_deps}
extra_scripts = ${common.extra_scripts}
monitor_filters = esp32_exception_decoder

[env:heltec_wifi_lora_32_V3]
framework = arduino
platform = espressif32
; Use the pioarduino fork for Arduino Core 3.x / ESP-IDF 5.x support
;platform = https://github.com/pioarduino/platform-espressif32/releases/download/51.03.07/platform-espressif32.zip
;platform = https://github.com/pioarduino/platform-espressif32/releases/download/53.03.13/platform-espressif32.zip
; Very stable
;platform = https://github.com/pioarduino/platform-espressif32/releases/download/54.03.21-2/platform-espressif32.zip
; Latest stable
;platform = https://github.com/pioarduino/platform-espressif32/releases/download/55.03.32/platform-espressif32.zip
board = heltec_wifi_lora_32_V3
;board_build.partitions = partitions_esp32.csv
board_build.partitions = no_ota.csv
board_upload.flash_size = 8MB
board_build.filesystem = littlefs
build_unflags =
    ${common.build_unflags}
build_flags =
    ${common.build_flags}
    -DPLATFORM_ESP32
    -DARDUINO_USB_CDC_ON_BOOT=1
    -DUSTORE_USE_LITTLEFS
    -DUSTORE_USE_SPIFFS
    -DUSTORE_USE_UNIVERSALFS
lib_deps =
    ${common.lib_deps}
extra_scripts = ${common.extra_scripts}
monitor_filters = esp32_exception_decoder

[env:wiscore_rak4631]
framework = arduino
platform = nordicnrf52
;board = wiscore_rak4631
board = rak4630
board_build.variants_dir = variants
board_build.variant = rak4630
board_build.partitions = no_ota.csv
build_unflags =
    ${common.build_unflags}
build_flags =
    ${common.build_flags}
    -DLFS_NO_ASSERT
    -DPLATFORM_NRF52
    -DUSTORE_USE_INTERNALFS
    -DUSTORE_USE_FLASHFS
    -DUSTORE_USE_UNIVERSALFS
lib_deps =
    ${common.lib_deps}
    adafruit/SdFat - Adafruit Fork
    https://github.com/attermann/Adafruit_SPIFlash#littlefs
extra_scripts = ${common.extra_scripts}
